import type { Metadata } from "next";
import { CartProvider } from "@/context/CartContext";
import "./globals.css";


export const metadata: Metadata = {
  title: "E-commerce Product Page",
  description: "Generated by Iyanuoluwa Pelumi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
