import type { Metadata } from "next";
import { CartProvider } from "@/components/CartContext";
import "./globals.css";


export const metadata: Metadata = {
  title: "E-commerce Product Page",
  description: "Generated by Iyanuoluwa Pelumi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <CartProvider>
          {children}
        </CartProvider>

        {/* Footer */}
        <footer className="bg-gray-200 text-center py-4 bottom-0 w-full">
          <p className="text-gray-600"> © Iyanuoluwa Pelumi. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
